server:
  port: 8089


spring:
  datasource:
    url: jdbc:mysql://rdsxt5l78bid42x9ddylc832.mysql.rds.aliyuncs.com:3306/yt_edp_dev?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: yangtuojia001
    password: yangtuojia001
    driver-class-name: com.mysql.jdbc.Driver

